export const RecJob = [
  {
    id: "1",
    date: "jul 21, 2023",
    title: "Front-end Developer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
  {
    id: "2",
    date: "jul 15, 2023",
    title: "Front-end Developer",
    companyName: "IBM",
    experience: "0- yrs",
    city: "Dehradun",
  },
  {
    id: "3",
    date: "jul 21, 2023",
    title: "UI/UX designer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
  {
    id: "4",
    date: "jul 21, 2023",
    title: "Front-end Developer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
  {
    id: "5",
    date: "jul 21, 2023",
    title: "Front-end Developer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
  {
    id: "6",
    date: "jul 21, 2023",
    title: "Front-end Developer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
  {
    id: "7",
    date: "jul 21, 2023",
    title: "Front-end Developer",
    companyName: "Google",
    experience: "0-5 yrs",
    city: "Dehradun",
  },
];

export const popularJobs = [
  { id: 1, title: "Software Developer", number: 15 },
  { id: 2, title: "Data Analyst", number: 8 },
  { id: 3, title: "Registered Nurse", number: 12 },
  { id: 4, title: "Marketing Manager", number: 6 },
  { id: 5, title: "Graphic Designer", number: 7 },
  { id: 6, title: "Teacher", number: 10 },
  { id: 7, title: "Sales Representative", number: 14 },
  { id: 8, title: "Civil Engineer", number: 5 },
  { id: 9, title: "Financial Analyst", number: 9 },
];

export const featuredJobs = [
  {
    id: 1,
    title: "Software Development",
    cat: "Segment",
    location: "London, UK",
    time: "11 hours ago",
    salary: "$30k-35k",
    type: ["Part-time", "Full-Time", "Urgent"],
  },
  {
    id: 2,
    title: "Marketing Specialist",
    cat: "Catalyst",
    location: "New York, USA",
    time: "1 day ago",
    salary: "$40k-45k",
    type: ["Full-Time"],
  },
  {
    id: 3,
    title: "UX/UI Designer",
    cat: "Segment",
    location: "San Francisco, USA",
    time: "2 days ago",
    salary: "$50k-60k",
    type: ["Full-Time"],
  },
  {
    id: 4,
    title: "Security Analyst",
    cat: "Segment",
    location: "Toronto, Canada",
    time: "3 days ago",
    salary: "$55k-65k",
    type: ["Full-Time", "Remote"],
  },
  {
    id: 5,
    title: "Content Writer",
    cat: "Catalyst",
    location: "Sydney, Australia",
    time: "4 days ago",
    salary: "$25k-30k",
    type: ["Part-time", "Remote"],
  },
  {
    id: 6,
    title: "Data Scientist",
    cat: "Segment",
    location: "Berlin, Germany",
    time: "5 days ago",
    salary: "$60k-70k",
    type: ["Full-Time"],
  },
  {
    id: 7,
    title: "Customer Support Representative",
    cat: "Segment",
    location: "Tokyo, Japan",
    time: "6 days ago",
    salary: "$28k-32k",
    type: ["Full-Time"],
  },
  {
    id: 8,
    title: "Product Manager",
    cat: "Catalyst",
    location: "Seattle, USA",
    time: "1 week ago",
    salary: "$70k-80k",
    type: ["Full-Time"],
  },
  {
    id: 9,
    title: "Electrical Engineer",
    cat: "Segment",
    location: "Beijing, China",
    time: "1 week ago",
    salary: "$45k-55k",
    type: ["Full-Time"],
  },
  {
    id: 10,
    title: "Digital Marketing Specialist",
    cat: "Catalyst",
    location: "Paris, France",
    time: "1 week ago",
    salary: "$50k-60k",
    type: ["Full-Time", "Remote"],
  },
];

export const jobDesc = {
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla aliquet enim tortor at auctor urna nunc id. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Nibh cras pulvinar mattis nunc sed.",
  responsibility:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla aliquet enim tortor at auctor urna nunc id. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Nibh cras pulvinar mattis nunc sed.",

  skills:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla aliquet enim tortor at auctor urna nunc id. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Nibh cras pulvinar mattis nunc sed.",
};
